# Generated by Django 5.1 on 2024-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_table',
            name='new_task',
            field=models.BooleanField(default=False),
        ),
    ]
