# Generated by Django 5.1 on 2024-09-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0002_task_table_new_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_table',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
